version: '3'

services:
  bexy-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8001:8001"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - DEBUG=True
    command: |
      bash -c "python -m pytest tests/ -v --junitxml=/app/test-reports/test-results.xml"

  bexy-mock:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8001:8001"
    volumes:
      - ./tests:/app/tests
      - ./test-reports:/app/test-reports
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - DEBUG=True
    command: |
      bash -c "python -m bexy.app --port 8001 --host 0.0.0.0"

volumes:
  test-reports:
